In [1]:
import pandas as pd

In [2]:
df = pd.read_pickle("../data/Khovanov/even_KH.pkl")
df

,knot_id,number_of_crossings,is_alternating,s_invariant,signature,F_q-35_t-13,F_q-33_t-13,F_q-33_t-12,F_q-31_t-13,F_q-31_t-12,...,T4_q-13_t-4,T4_q-11_t-4,T4_q11_t5,T4_q13_t5,T4_q15_t5,T4_q17_t5,T4_q21_t9,T4_q23_t9,T4_q25_t9,T4_q27_t9
0,00_1,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,03_1,3,1,2,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,04_1,4,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,05_1,5,1,4,4,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,05_2,5,1,2,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9755324,17nh_6283381,17,0,-2,-2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9755325,17nh_6283382,17,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9755326,17nh_6283383,17,0,-6,-6,0,24,0,7,58,...,0,0,0,0,0,0,0,0,0,0
9755327,17nh_6283384,17,0,2,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9755328,17nh_6283385,17,0,2,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
df.to_csv("../data/Khovanov/even_KH_upto17.csv", index=False)